name: Java CI with Gradle  # Название вашего workflow

on:  # Определяет, когда будет запускаться workflow
  push:
    branches: [ main, feature/* ]  # При push в ветку main или любую feature-ветку
  pull_request:
    branches: [ main ]  # При создании PR в main

jobs:  # Задачи, которые будут выполняться
  build:  # Название задачи
    runs-on: ubuntu-latest  # На какой ОС будет выполняться (исправил alpine на ubuntu)

    steps:  # Шаги выполнения
      - uses: actions/checkout@v3  # Клонирование репозитория

      - name: Set up JDK 21  # Установка Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Prepare  # Подготовка Предоставление прав на выполнение
        run: chmod +x gradlew

      - name: Build without tests  # Сборка проекта без тестов
        run: ./gradlew clean build -x test

      - name: Run tests  # Запуск тестов
        run: ./gradlew test

      - name: Clean and build  # Очистка и полная сборка проекта
        run: ./gradlew clean build